# Capture Biomes Plugin Configuration

enabled: true                         # enable or disable the plugin's basic functionalities
                                      # commands as well as update services will still work
                                      # boolean (true / false)
                                      # can also be changed in game via /capturebiomes enable or /capturebiomes disable

# --- Beacon ritual items ---
beacon:
  required-item-count:                # items required for every beacon level (cannot be more than 64)
                                      # Have to be > 0
    tier-1: 16
    tier-2: 32
    tier-3: 48
    tier-4: 64
  biome-potions-size:                 # Effect range of the Biome Potion when used (squared → 4 = 4x4 blocks)
                                      # Have to be whole and even numbers
                                      # Have to be > 0
                                      # See https://github.com/mxiwbr/capture-biomes/blob/main/README.md to understand how the size works
    tier-1: 4
    tier-2: 8
    tier-3: 16
    tier-4: 32
  trigger_item: EXPERIENCE_BOTTLE     # The item that must be thrown on the beacon to trigger the biome capture
                                      # See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html for the item names
  biome-potions-amount: 1             # amount of Biome Potions to get each time
                                      # default: 1
                                      # Has to be > 0

# --- Biome Potions ---
potion-cooldown:                      # cooldown of the biome potions
                                      # this affects all potions created after changing this value - old items will still have the same cooldown settings!
                                      # recommended to leave enabled to prevent players from crashing / lagging the server by throwing too many potions at once

  enabled: true                       # default: true
                                      # boolean (true / false)

  length: 15                          # default: 15
                                      # full seconds
                                      # Has to be > 0. To disable it completely, please set potion-cooldown.enabled to false
                                      # only relevant if enabled is true

### ADVANCED SETTINGS – only change if you know what you're doing! ###

# --- Console Logging ---
console:
  enable-logging: true                # default: true
                                      # boolean (true / false)
                                      # if you set this to false, all console logging will be disabled. This includes all info logs as well as warnings and severe errors

  enable-additional-logging: false    # default: false
                                      # will enable additional logging whenever an action is done by the plugin, like creating or releasing a biome potion
                                      # only relevant if enable-logging is true

# --- Item checking (for XP bottles on beacon) ---
item-check:
  timeout-ticks: 200                  # How long the plugin checks for each item being on ground in ticks (20 ticks = 1 second)
                                      # Has to be > 0
  interval-ticks: 2                   # Interval between each check in ticks (20 ticks = 1 second)
                                      # Has to be > 0

# --- bStats ---
bstats:
  enabled: true                       # default: true
                                      # enables / disables sending anonymous data like amount of servers using the plugin to bStats
                                      # see README.md section "bStats" for more information