# Capture Biomes Plugin Configuration

# --- Beacon ritual items ---
beacon:
  required-xp-bottles:                # XP bottles required for every beacon level (cannot be more than 64)
    tier-1: 16
    tier-2: 32
    tier-3: 48
    tier-4: 64
  biome-potions-size:                 # Effect range of the Biome Potion when used (squared → 4 = 4x4 blocks)
                                      # Has to be a whole and even number (e.g. 4 ✅, 7 ❌, 4.5 ❌)
                                      # See https://github.com/mxiwbr/capture-biomes/blob/main/README.md to understand how the size works
    tier-1: 4
    tier-2: 8
    tier-3: 16
    tier-4: 32
  trigger_item: EXPERIENCE_BOTTLE     # The item that must be thrown on the beacon to trigger the biome capture
                                      # See https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html for the item names
  biome-potions-amount: 1             #  default: 1 | amount of Biome Potions to get each time

# --- Biome Potions ---
potion-cooldown:                      # cooldown of the biome potions
                                      # recommended to leave enabled to prevent players from crashing / lagging the server by throwing too many potions at once

  enabled: true                       # default: true
                                      # boolean (true / false)

  length: 15                          # default: 15
                                      # full seconds
                                      # only relevant if enabled is true

# --- Advanced settings – only change if you know what you're doing ---

# --- Item checking (for XP bottles on beacon) ---
item-check:
  timeout-ticks: 200                  # How long the plugin checks for each item being on ground in ticks (20 ticks = 1 second)
  interval-ticks: 2                   # Interval between each check in ticks (20 ticks = 1 second)
